[workspace]

[package]
name = "viewer"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
appcore = { package = "mochios-appcore", path = "../../tools/devkit/crates/appcore" }

[[bin]]
name = "viewer"
path = "src/main.rs"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(target_os, values("mochios"))'] }
